complexity:
  ComplexCondition:
    threshold: 6
  CyclomaticComplexMethod:
    threshold: 25
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    max: 10
